In [58]:
import pandas as pd

df=pd.read_csv('signLanguageDatset2.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,label
0,"[0, 472, 329]","[1, 431, 312]","[2, 403, 276]","[3, 393, 237]","[4, 394, 207]","[5, 423, 241]","[6, 417, 212]","[7, 420, 244]","[8, 425, 257]","[9, 447, 241]",...,"[12, 446, 260]","[13, 472, 246]","[14, 466, 224]","[15, 462, 262]","[16, 466, 268]","[17, 497, 251]","[18, 489, 235]","[19, 482, 261]","[20, 486, 268]",0
1,"[0, 471, 326]","[1, 431, 312]","[2, 405, 275]","[3, 397, 236]","[4, 395, 206]","[5, 424, 240]","[6, 419, 212]","[7, 423, 244]","[8, 428, 257]","[9, 449, 241]",...,"[12, 448, 261]","[13, 473, 245]","[14, 468, 225]","[15, 464, 262]","[16, 467, 268]","[17, 497, 251]","[18, 491, 236]","[19, 486, 261]","[20, 488, 267]",0
2,"[0, 470, 326]","[1, 431, 312]","[2, 405, 275]","[3, 397, 236]","[4, 395, 206]","[5, 424, 240]","[6, 420, 212]","[7, 423, 244]","[8, 428, 258]","[9, 449, 241]",...,"[12, 448, 261]","[13, 473, 245]","[14, 468, 225]","[15, 464, 262]","[16, 468, 268]","[17, 497, 251]","[18, 491, 236]","[19, 485, 260]","[20, 488, 266]",0
3,"[0, 470, 326]","[1, 431, 311]","[2, 405, 274]","[3, 397, 236]","[4, 395, 207]","[5, 424, 240]","[6, 420, 212]","[7, 424, 244]","[8, 428, 259]","[9, 449, 240]",...,"[12, 448, 261]","[13, 473, 245]","[14, 468, 224]","[15, 464, 262]","[16, 468, 268]","[17, 497, 251]","[18, 491, 236]","[19, 485, 260]","[20, 488, 266]",0
4,"[0, 471, 325]","[1, 432, 310]","[2, 407, 274]","[3, 398, 236]","[4, 396, 207]","[5, 425, 239]","[6, 421, 212]","[7, 424, 243]","[8, 429, 258]","[9, 450, 240]",...,"[12, 450, 260]","[13, 474, 245]","[14, 469, 225]","[15, 465, 261]","[16, 469, 267]","[17, 498, 250]","[18, 492, 236]","[19, 486, 259]","[20, 489, 265]",0

In [14]:
df2=pd.DataFrame()

In [17]:
for col in df.columns:
    df[col]=df[col].astype(str).fillna('')

In [59]:
df2=pd.DataFrame()

for col in df.columns:
    if col == "label":
        continue
    first=col+'x'
    second=col+'y'
    df2[first]=df[col].str.strip('[]').str.split(',').str[1].astype('int')
    df2[second]=df[col].str.strip('[]').str.split(',').str[2].astype('int')
    
df2['label']=df['label'].astype('int')  

df2.head()

,0x,0y,1x,1y,2x,2y,3x,3y,4x,4y,...,16y,17x,17y,18x,18y,19x,19y,20x,20y,label
0,472,329,431,312,403,276,393,237,394,207,...,268,497,251,489,235,482,261,486,268,0
1,471,326,431,312,405,275,397,236,395,206,...,268,497,251,491,236,486,261,488,267,0
2,470,326,431,312,405,275,397,236,395,206,...,268,497,251,491,236,485,260,488,266,0
3,470,326,431,311,405,274,397,236,395,207,...,268,497,251,491,236,485,260,488,266,0
4,471,325,432,310,407,274,398,236,396,207,...,267,498,250,492,236,486,259,489,265,0

In [26]:
df2.tail()

,0x,0y,1x,1y,2x,2y,3x,3y,4x,4y,...,16y,17x,17y,18x,18y,19x,19y,20x,20y,label
295,543,334,496,324,455,304,423,293,397,276,...,157,526,236,507,203,489,185,470,171,2
296,543,334,496,324,455,304,422,293,397,275,...,156,526,235,507,202,489,184,470,170,2
297,543,334,496,324,455,304,423,293,397,275,...,157,526,235,507,202,489,184,470,170,2
298,544,334,497,325,455,304,423,293,397,275,...,157,527,235,507,202,489,184,470,171,2
299,544,334,497,325,455,304,423,293,397,275,...,157,527,235,507,202,489,184,470,171,2

In [60]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 43 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0x      300 non-null    int32
 1   0y      300 non-null    int32
 2   1x      300 non-null    int32
 3   1y      300 non-null    int32
 4   2x      300 non-null    int32
 5   2y      300 non-null    int32
 6   3x      300 non-null    int32
 7   3y      300 non-null    int32
 8   4x      300 non-null    int32
 9   4y      300 non-null    int32
 10  5x      300 non-null    int32
 11  5y      300 non-null    int32
 12  6x      300 non-null    int32
 13  6y      300 non-null    int32
 14  7x      300 non-null    int32
 15  7y      300 non-null    int32
 16  8x      300 non-null    int32
 17  8y      300 non-null    int32
 18  9x      300 non-null    int32
 19  9y      300 non-null    int32
 20  10x     300 non-null    int32
 21  10y     300 non-null    int32
 22  11x     300 non-null    int32
 23  11y     300 non-null    int32
 24  12x     300 non-null    int32
 25  12y     300 non-null    int32
 26  13x     300 non-null    int32
 27  13y     300 non-null    int32
 28  14x     300 non-null    int32
 29  14y     300 non-null    int32
 30  15x     300 non-null    int32
 31  15y     300 non-null    int32
 32  16x     300 non-null    int32
 33  16y     300 non-null    int32
 34  17x     300 non-null    int32
 35  17y     300 non-null    int32
 36  18x     300 non-null    int32
 37  18y     300 non-null    int32
 38  19x     300 non-null    int32
 39  19y     300 non-null    int32
 40  20x     300 non-null    int32
 41  20y     300 non-null    int32
 42  label   300 non-null    int32
dtypes: int32(43)
memory usage: 50.5 KB

In [61]:
from sklearn.model_selection import train_test_split
import numpy as np

X=df2.iloc[:,:-1].values
y=df2['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)

X_train = X_train / np.max(X_train)
X_test = X_test / np.max(X_test)

len(X_train),len(X_test)

(240, 60)

In [62]:
len(df2['label'].unique())

3

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

classes=len(df2['label'].unique())

model = Sequential([
    Dense(128, activation='relu', input_shape=(42,)),  
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(classes, activation='softmax')  
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=30, validation_data=(X_test, y_test))

Epoch 1/50

c:\Users\Vansh\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.2980 - loss: 1.1662 - val_accuracy: 0.3667 - val_loss: 1.0894
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3870 - loss: 1.0822 - val_accuracy: 0.3167 - val_loss: 1.0697
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4579 - loss: 1.0721 - val_accuracy: 0.4167 - val_loss: 1.0366
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5312 - loss: 1.0273 - val_accuracy: 0.8000 - val_loss: 0.9814
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5817 - loss: 0.9998 - val_accuracy: 0.8333 - val_loss: 0.9326
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6339 - loss: 0.9609 - val_accuracy: 0.8500 - val_loss: 0.8786
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6285 - loss: 0.9075 - val_accuracy: 0.5000 - val_loss: 0.8614
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6424 - loss: 0.8546 - val_accuracy: 0.9000 - val_loss: 0.7262
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6918 - loss: 0.7969 - val_accuracy: 0.5167 - val_loss: 0.7684
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7022 - loss: 0.7209 - val_accuracy: 0.9167 - val_loss: 0.6047
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7266 - loss: 0.6860 - val_accuracy: 0.9167 - val_loss: 0.5610
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8367 - loss: 0.5829 - val_accuracy: 0.9167 - val_loss: 0.5143
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8410 - loss: 0.5258 - val_accuracy: 0.9833 - val_loss: 0.4192
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.4910 - val_accuracy: 1.0000 - val_loss: 0.3646
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8732 - loss: 0.4452 - val_accuracy: 1.0000 - val_loss: 0.3107
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8662 - loss: 0.4110 - val_accuracy: 1.0000 - val_loss: 0.2706
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9180 - loss: 0.3435 - val_accuracy: 1.0000 - val_loss: 0.2159
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9591 - loss: 0.2569 - val_accuracy: 1.0000 - val_loss: 0.1944
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9642 - loss: 0.2506 - val_accuracy: 1.0000 - val_loss: 0.1653
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9347 - loss: 0.2506 - val_accuracy: 1.0000 - val_loss: 0.1276
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.1910 - val_accuracy: 1.0000 - val_loss: 0.1025
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9694 - loss: 0.1612 - val_accuracy: 1.0000 - val_loss: 0.0910
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9950 - loss: 0.1315 - val_accuracy: 1.0000 - val_loss: 0.0619
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9986 - loss: 0.0961 - val_accuracy: 1.0000 - val_loss: 0.0549
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9939 - loss: 0.1050 - val_accuracy: 1.0000 - val_loss: 0.0389
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9857 - loss: 0.0933 - val_accuracy: 1.0000 - val_loss: 0.0360
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0676 - val_accuracy: 1.0000 - val_loss: 0.0265
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0566 - val_accuracy: 1.0000 - val_loss: 0.0208
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0541 - val_accuracy: 1.0000 - val_loss: 0.0228
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9836 - loss: 0.0592 - val_accuracy: 1.0000 - val_loss: 0.0152
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9901 - loss: 0.0506 - val_accuracy: 1.0000 - val_loss: 0.0129
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0383 - val_accuracy: 1.0000 - val_loss: 0.0131
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0355 - val_accuracy: 1.0000 - val_loss: 0.0113
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9953 - loss: 0.0368 - val_accuracy: 1.0000 - val_loss: 0.0086
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9986 - loss: 0.0229 - val_accuracy: 1.0000 - val_loss: 0.0102
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0238 - val_accuracy: 1.0000 - val_loss: 0.0064
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9964 - loss: 0.0208 - val_accuracy: 1.0000 - val_loss: 0.0076
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0306 - val_accuracy: 1.0000 - val_loss: 0.0065
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0210 - val_accuracy: 1.0000 - val_loss: 0.0050
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9953 - loss: 0.0230 - val_accuracy: 1.0000 - val_loss: 0.0049
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0136 - val_accuracy: 1.0000 - val_loss: 0.0037
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9980 - loss: 0.0193 - val_accuracy: 1.0000 - val_loss: 0.0068
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0332 - val_accuracy: 1.0000 - val_loss: 0.0041
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9901 - loss: 0.0234 - val_accuracy: 1.0000 - val_loss: 0.0032
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0178 - val_accuracy: 1.0000 - val_loss: 0.0027
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0112 - val_accuracy: 1.0000 - val_loss: 0.0022
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0094 - val_accuracy: 1.0000 - val_loss: 0.0021
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0080 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0094 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0145 - val_accuracy: 1.0000 - val_loss: 0.0017

In [64]:
predictions = model.predict(X_test)
predicted_classes = tf.argmax(predictions, axis=-1)
predicted_classes[:5]

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step

In [65]:
from sklearn.metrics import classification_report
report=classification_report(y_test,predicted_classes)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        22

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60

In [67]:
import joblib

joblib.dump(model,'modelV1.pkl')

['modelV1.pkl']