In [99]:
import pandas as pd

df=pd.read_csv('signLanguageDatset2.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,label
0,"[0, 508, 289]","[1, 469, 283]","[2, 440, 255]","[3, 430, 223]","[4, 425, 199]","[5, 451, 220]","[6, 448, 197]","[7, 455, 225]","[8, 457, 231]","[9, 473, 217]",...,"[12, 473, 230]","[13, 494, 217]","[14, 493, 197]","[15, 493, 230]","[16, 494, 231]","[17, 515, 218]","[18, 513, 206]","[19, 510, 230]","[20, 511, 234]",0
1,"[0, 507, 289]","[1, 468, 283]","[2, 439, 255]","[3, 430, 221]","[4, 426, 199]","[5, 450, 220]","[6, 447, 198]","[7, 454, 225]","[8, 457, 232]","[9, 473, 216]",...,"[12, 473, 231]","[13, 495, 216]","[14, 492, 197]","[15, 492, 229]","[16, 493, 231]","[17, 516, 217]","[18, 512, 205]","[19, 510, 228]","[20, 512, 232]",0
2,"[0, 508, 289]","[1, 469, 284]","[2, 438, 255]","[3, 429, 221]","[4, 426, 198]","[5, 450, 220]","[6, 447, 198]","[7, 455, 226]","[8, 457, 232]","[9, 473, 216]",...,"[12, 473, 231]","[13, 494, 216]","[14, 492, 197]","[15, 493, 229]","[16, 493, 231]","[17, 516, 216]","[18, 513, 205]","[19, 511, 228]","[20, 512, 232]",0
3,"[0, 507, 289]","[1, 467, 284]","[2, 438, 255]","[3, 429, 221]","[4, 425, 199]","[5, 450, 220]","[6, 446, 197]","[7, 454, 225]","[8, 457, 233]","[9, 473, 217]",...,"[12, 473, 231]","[13, 494, 216]","[14, 491, 197]","[15, 492, 229]","[16, 493, 231]","[17, 516, 217]","[18, 512, 206]","[19, 510, 229]","[20, 512, 232]",0
4,"[0, 507, 289]","[1, 468, 284]","[2, 438, 255]","[3, 429, 221]","[4, 425, 198]","[5, 450, 220]","[6, 446, 198]","[7, 454, 225]","[8, 457, 233]","[9, 473, 217]",...,"[12, 473, 232]","[13, 494, 216]","[14, 492, 198]","[15, 492, 230]","[16, 493, 232]","[17, 516, 217]","[18, 512, 206]","[19, 510, 229]","[20, 511, 233]",0

In [30]:
df2=pd.DataFrame()

In [101]:
for col in df.columns:
    df[col]=df[col].astype(str).fillna('')

In [ ]:
import numpy as np
import pandas as pd

def calculate_angle(a, b, c):
    a = np.array(a)
    b = np.array(b)
    c = np.array(c)
    
    ba = a - b
    bc = c - b
    
    cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))
    cosine_angle = np.clip(cosine_angle, -1.0, 1.0)
    
    angle = np.arccos(cosine_angle)
    return np.degrees(angle)

df2=pd.DataFrame()
df3=pd.DataFrame()

for col in df.columns:
    if col == "label":
        continue
    first=col+'x'
    second=col+'y'
    speed_col=col
    df2[first]=df[col].str.strip('[]').str.split(',').str[1].astype('int')
    df2[second]=df[col].str.strip('[]').str.split(',').str[2].astype('int')
    # df2[speed_col] = np.sqrt(df3[first].diff()**2 + df3[second].diff()**2)
    # df2[col+'diffX'] = df2[first].diff()
    # df2[col+'diffY'] = df2[second].diff()
    col_int=int(col)
    # if col_int > 0 and col_int < 20 :
    #     df2['angle' + str(col)] = df.apply(
    #         lambda row: calculate_angle(
    #             [int(x) for x in row[str(col_int - 1)].strip('[]').split(',')[1:]],  # previous landmark
    #             [int(x) for x in row[str(col_int)].strip('[]').split(',')[1:]],      # current landmark
    #             [int(x) for x in row[str(col_int + 1)].strip('[]').split(',')[1:]]     # next landmark
    #         ),
    #         axis=1
    #     )
    
df2['label']=df['label'].astype('int')  

df2.head()

,0x,0y,1x,1y,2x,2y,3x,3y,4x,4y,...,16y,17x,17y,18x,18y,19x,19y,20x,20y,label
0,508,289,469,283,440,255,430,223,425,199,...,231,515,218,513,206,510,230,511,234,0
1,507,289,468,283,439,255,430,221,426,199,...,231,516,217,512,205,510,228,512,232,0
2,508,289,469,284,438,255,429,221,426,198,...,231,516,216,513,205,511,228,512,232,0
3,507,289,467,284,438,255,429,221,425,199,...,231,516,217,512,206,510,229,512,232,0
4,507,289,468,284,438,255,429,221,425,198,...,232,516,217,512,206,510,229,511,233,0

In [117]:
df2.tail()

,0x,0y,1x,1y,2x,2y,3x,3y,4x,4y,...,16y,17x,17y,18x,18y,19x,19y,20x,20y,label
3995,567,187,549,149,510,131,469,137,444,143,...,164,485,159,466,181,481,187,494,183,7
3996,566,186,548,149,510,130,468,135,443,141,...,163,485,157,465,181,480,188,494,184,7
3997,566,186,548,149,509,130,467,136,442,142,...,164,485,156,465,180,480,188,494,184,7
3998,565,187,547,150,508,131,466,138,440,144,...,165,485,158,464,181,480,188,494,184,7
3999,565,188,547,150,508,131,466,137,441,143,...,165,484,159,464,180,480,187,493,184,7

In [118]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 43 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0x      4000 non-null   int32
 1   0y      4000 non-null   int32
 2   1x      4000 non-null   int32
 3   1y      4000 non-null   int32
 4   2x      4000 non-null   int32
 5   2y      4000 non-null   int32
 6   3x      4000 non-null   int32
 7   3y      4000 non-null   int32
 8   4x      4000 non-null   int32
 9   4y      4000 non-null   int32
 10  5x      4000 non-null   int32
 11  5y      4000 non-null   int32
 12  6x      4000 non-null   int32
 13  6y      4000 non-null   int32
 14  7x      4000 non-null   int32
 15  7y      4000 non-null   int32
 16  8x      4000 non-null   int32
 17  8y      4000 non-null   int32
 18  9x      4000 non-null   int32
 19  9y      4000 non-null   int32
 20  10x     4000 non-null   int32
 21  10y     4000 non-null   int32
 22  11x     4000 non-null   int32
 23  11y     4000 non-null   int32
 24  12x     4000 non-null   int32
 25  12y     4000 non-null   int32
 26  13x     4000 non-null   int32
 27  13y     4000 non-null   int32
 28  14x     4000 non-null   int32
 29  14y     4000 non-null   int32
 30  15x     4000 non-null   int32
 31  15y     4000 non-null   int32
 32  16x     4000 non-null   int32
 33  16y     4000 non-null   int32
 34  17x     4000 non-null   int32
 35  17y     4000 non-null   int32
 36  18x     4000 non-null   int32
 37  18y     4000 non-null   int32
 38  19x     4000 non-null   int32
 39  19y     4000 non-null   int32
 40  20x     4000 non-null   int32
 41  20y     4000 non-null   int32
 42  label   4000 non-null   int32
dtypes: int32(43)
memory usage: 672.0 KB

In [119]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

X=df2.iloc[:,:-1].values
y=df2['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

len(X_train),len(X_test)

(3200, 800)

In [114]:
len(df2['label'].unique())

8

In [120]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

classes=len(df2['label'].unique())

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.4),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),
    Dense(32, activation='relu'),
    Dense(classes, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=40, validation_data=(X_test, y_test))

Epoch 1/40

c:\Users\Vansh\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3575 - loss: 1.8496 - val_accuracy: 0.8138 - val_loss: 1.1737
Epoch 2/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8798 - loss: 0.4679 - val_accuracy: 0.9925 - val_loss: 0.3739
Epoch 3/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9760 - loss: 0.1424 - val_accuracy: 0.9950 - val_loss: 0.0764
Epoch 4/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9908 - loss: 0.0621 - val_accuracy: 1.0000 - val_loss: 0.0160
Epoch 5/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9895 - loss: 0.0486 - val_accuracy: 1.0000 - val_loss: 0.0040
Epoch 6/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0306 - val_accuracy: 0.9937 - val_loss: 0.0159
Epoch 7/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9927 - loss: 0.0280 - val_accuracy: 1.0000 - val_loss: 8.4766e-04
Epoch 8/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9956 - loss: 0.0229 - val_accuracy: 1.0000 - val_loss: 4.7515e-04
Epoch 9/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0194 - val_accuracy: 1.0000 - val_loss: 8.5115e-04
Epoch 10/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9907 - loss: 0.0312 - val_accuracy: 1.0000 - val_loss: 2.9855e-04
Epoch 11/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9967 - loss: 0.0144 - val_accuracy: 1.0000 - val_loss: 5.4907e-04
Epoch 12/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9953 - loss: 0.0145 - val_accuracy: 0.9950 - val_loss: 0.0094
Epoch 13/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9927 - loss: 0.0249 - val_accuracy: 1.0000 - val_loss: 8.3629e-04
Epoch 14/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9952 - loss: 0.0159 - val_accuracy: 1.0000 - val_loss: 6.2628e-05
Epoch 15/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9927 - loss: 0.0199 - val_accuracy: 1.0000 - val_loss: 7.7691e-05
Epoch 16/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0211 - val_accuracy: 1.0000 - val_loss: 1.2031e-04
Epoch 17/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9951 - loss: 0.0139 - val_accuracy: 1.0000 - val_loss: 2.2692e-04
Epoch 18/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9981 - loss: 0.0086 - val_accuracy: 1.0000 - val_loss: 4.9667e-04
Epoch 19/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9963 - loss: 0.0149 - val_accuracy: 1.0000 - val_loss: 2.7084e-04
Epoch 20/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9952 - loss: 0.0168 - val_accuracy: 1.0000 - val_loss: 6.3679e-05
Epoch 21/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9971 - loss: 0.0107 - val_accuracy: 1.0000 - val_loss: 4.3380e-05
Epoch 22/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9937 - loss: 0.0209 - val_accuracy: 1.0000 - val_loss: 1.8426e-04
Epoch 23/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9891 - loss: 0.0321 - val_accuracy: 1.0000 - val_loss: 1.0247e-04
Epoch 24/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9948 - loss: 0.0187 - val_accuracy: 1.0000 - val_loss: 8.0037e-05
Epoch 25/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0120 - val_accuracy: 1.0000 - val_loss: 7.7141e-05
Epoch 26/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0085 - val_accuracy: 1.0000 - val_loss: 2.2134e-05
Epoch 27/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0062 - val_accuracy: 1.0000 - val_loss: 4.0901e-05
Epoch 28/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0082 - val_accuracy: 1.0000 - val_loss: 6.9589e-05
Epoch 29/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9994 - loss: 0.0043 - val_accuracy: 1.0000 - val_loss: 4.1238e-05
Epoch 30/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9953 - loss: 0.0109 - val_accuracy: 1.0000 - val_loss: 7.8175e-06
Epoch 31/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0058 - val_accuracy: 0.9987 - val_loss: 0.0024
Epoch 32/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9930 - loss: 0.0206 - val_accuracy: 1.0000 - val_loss: 4.9465e-05
Epoch 33/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9976 - loss: 0.0103 - val_accuracy: 1.0000 - val_loss: 3.6341e-04
Epoch 34/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9979 - loss: 0.0074 - val_accuracy: 1.0000 - val_loss: 5.4609e-05
Epoch 35/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0084 - val_accuracy: 1.0000 - val_loss: 5.2372e-06
Epoch 36/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9992 - loss: 0.0030 - val_accuracy: 1.0000 - val_loss: 4.7721e-06
Epoch 37/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0019 - val_accuracy: 1.0000 - val_loss: 9.0870e-06
Epoch 38/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9978 - loss: 0.0038 - val_accuracy: 1.0000 - val_loss: 6.9066e-06
Epoch 39/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9998 - loss: 0.0015 - val_accuracy: 1.0000 - val_loss: 1.1968e-05
Epoch 40/40
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9994 - loss: 0.0023 - val_accuracy: 1.0000 - val_loss: 6.6285e-05

In [91]:
predictions = model.predict(X_test)
predicted_classes = tf.argmax(predictions, axis=-1)
predicted_classes[:5]

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [77]:
y_test[:5]

555     1
3491    6
527     1
3925    7
2989    4
Name: label, dtype: int32

In [92]:
from sklearn.metrics import classification_report
report=classification_report(y_test,predicted_classes)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       123
           1       0.00      0.00      0.00        86
           2       0.00      0.00      0.00       112
           3       0.00      0.00      0.00       101
           4       0.00      0.00      0.00        90
           5       0.00      0.00      0.00       104
           6       0.11      1.00      0.20        91
           7       0.00      0.00      0.00        93

    accuracy                           0.11       800
   macro avg       0.01      0.12      0.03       800
weighted avg       0.01      0.11      0.02       800

c:\Users\Vansh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Vansh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Vansh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [79]:
import joblib

joblib.dump(model,'modelV3.pkl')

['modelV3.pkl']